name: "Autobackup-Staging"
description: "Autobackup-Staging add-on"
version: "1.0.7"
slug: "autobackup"
init: false
hassio_api: true
homeassistant_api: true
hassio_role: "admin"
map:
  - backup:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/gordonampotech/autobackup-staging"
ingress: true
host_network: true
